# This is the configuration file of SIDAM. If you want to modify
# configurations, it is recommended to save a copy of this file as
# "SIDAM.toml" and modify it. You can place "SIDAM.toml" at the User
# Procedures folder or here. You need to call SIDAMsource() and compile
# to reflect the modifications.

# In the following, both an absolute path and a relative pass are
# accepted as a path. A relative path starts with ":" and is specified
# from the folder where the config file exists. Therefore, if you save
# "SIDAM.toml" at the User Procedures folder, you need to modify
# accordingly paths in the following.

[window]
# Width and height of an image window. The unit is points.
width = 200
height = 200
# Precision of the values shown in the control bar.
precision = 2

[window.colors]
# For general curves
line = [7967, 30583, 46260]
# For emphasized curves
line2 = [65535, 32639, 3598]
# For note
note = [11308, 41120, 11308]

[window.export]
# Make the background transparent, "graph", "window", or "both".
transparent = "both"
# Image resolution. If this is an integer n from 1 to 8, the actual
# resolution is n*72. Otherwise, this number is directly used.
resolution = 2

# Names of color table groups and paths to folders where color table
# waves exist. You can add your own group.
[ctab]
CartoColors = ":ctab:CartoColors"
CET = ":ctab:CET"
Cmocean = ":ctab:cmocean"
ColorBrewer = ":ctab:ColorBrewer"
Matplotlib = ":ctab:Matplotlib"
SciColMaps = ":ctab:SciColMaps"
SIDAM = ":ctab:SIDAM"

[loader]
# Paths to folders where data loading functions exist. Multiple folders
# can be given as a list separated with ";".
path = ":fileloader"

# Relationship extensions and loading functions.
[loader.functions]
# Nanonis sxm, nsp
"sxm,nsp" = "LoadNanonisSxmNsp"
# Nanonis dat
dat = "LoadNanonisDat"
# Nanonis 3ds
3ds = "LoadNanonis3ds"
# SM2
sm2 = "LoadRHKSM2"

[nanonis]
# The text encoding used when nanonis files were saved.
# If this item is empty, use the default text encoding of Igor Pro.
text_encoding = ""
# "m", "A", and "V" are used for length, current, and voltage
# in nanonis files. The following is to convert them to "nm", "nA",
# and "mV", respectively.
# If you prefer angstrom for length, use "\u00c5" for the unit and
# 1e10 for the scale.
length_unit = "nm"
length_scale = 1e9
current_unit = "nA"
current_scale = 1e9
voltage_unit = "mV"
voltage_scale = 1e3
conductance_unit = "nS"
conductance_scale = 1e9

[extension]
# Paths to extension folders. Files in the extension folders are loaded
# together with SIDAM files when SIDAM starts. If you have scripts using
# SIDAM functions, you may want to make an extension folder and put
# your script files in the folder. Multiple folders can be given as
# a list separated with ";".
path = ":func:experimental;"
