# Site settings
title: "SIDAM doc"
description: "SIDAM documents"
repository: "yuksk/SIDAM"
github_username: yuksk

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
search: true
search_full_content: true

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : "G-Y6G51RHYPS"
    anonymize_ip         : false

# Outputting
permalink: /:categories/:path/

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

atom_feed:
  hide: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yuksk/SIDAM"

collections:
  commands:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _commands
  - scope:
      path: ""
      type: commands
    values:
      layout: single
      toc: true
      toc_icon: list
      toc_sticky: true
      sidebar:
        nav: "commands"
